export enum ExceptionMessageCode {
    SUMMONER_NAME_NOT_FOUND = 'SUMMONER_NAME_NOT_FOUND',
    SUMMONER_DIVISION_ERROR = 'SUMMONER_DIVISION_ERROR',

    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    GENERAL_ERROR = 'GENERAL_ERROR',

    // temp
    API_ERROR_SOMETHING_WENT_WRONG = 'API_ERROR_SOMETHING_WENT_WRONG',
}
